### ISSUE TITLE
Language_id parameter has no effect on creation of object for FeathersJS app

### ISSUE THREAD

**Issue by lionelrudaz** [Digipolitan/sequelize-i18n#3]
Hi,

I've got an issue with the integration of sequelize-i18n on a FeathersJS app.

I've got a service called category. It's linked with a model called category. I can create new instance without any problem, but it always uses the default language I set.

Here's my repo: https://github.com/lionelrudaz/api.wellnow.ch

Here's what I send to create a new instance:

```
# Create a category
# 
curl -X "POST" "http://localhost:3030/categories" \
     -H "Accept-Language: fr" \
     -H "Content-Type: application/vnd.api+json" \
     -d "{\"rank\":\"12\",\"name\":\"Chiropractie\",\"slug\":\"physiotherapie\",\"language_id\":\"DE\"}"
```

I tried by sending language_id, lang and by defining Accept-Language. None of them work.

Do you have any clue?

Thanks in advance,

Lionel

**Comment by adriencamy** [comment]
Hi Lionel,

I'm not familiar with FeathersJS, but after a quick look at https://github.com/feathersjs/feathers-sequelize/blob/master/src/index.js#L88, it seems that it should work if you manage to pass a sequelize param.
It does work if you manualy set the param.sequelize to {llanguage_id: 'DE'} within the create function, so basically all you have to do is figure out a way to set this parameter correctly regarding your incoming request.

Moreover, this repo https://github.com/mapleinside/sequelize-i18n author is the holder of the npm package, so you should probably post your issues over there, since we won't be able to update the push any modification to npm in case you have a bug.

Adrien

**Comment by lionelrudaz** [comment]
Hi Adrien,

Thanks for your answer, sorry for my late reply. I had no time experimenting around that.

I tried a few stuff, but none of them worked. I'm contacting Sylvain to see if he has any clue. I close the issue for the moment.

Cheers,

Lionel
